[book]
authors = ["Seasawher"]
language = "en"
multilingual = false
src = "src"
title = "Mathlib4 Help"

[build]
create-missing = false
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/Seasawher/mathlib4-help"
site-url = "https://seasawher.github.io/mathlib4-help/"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
