[book]
authors = ["Seasawher"]
language = "en"
multilingual = false
src = "src"
title = "mathlib4 tactics"

[build]
create-missing = false
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/Seasawher/mathlib4-tactics"