site_name: Mathlib4 Help
site_url: https://seasawher.github.io/mathlib4-help/
nav:
  - attributes: attributes.md
  - commands: commands.md
  - options: options.md
  - tactics: tactics.md
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
