name: Generate markdown file

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lean action
        uses: leanprover/lean-action@main
        with:
          test: false
          use-github-cache: false

      - name: generate markdown file
        run: ./scripts/build.ps1
        shell: pwsh

      - name: run python script
        run: python3 script.py

      - name: find out if there are any changes. error if there are changes
        id: diff
        run: |
          git add -N src
          git diff --name-only --exit-code
        continue-on-error: true

      - name: commit if there are changes
        if: steps.diff.outcome == 'failure' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "generated by GitHub Action"
          git push

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.35'

      - name: build
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
